var sdkModelCrop = angular.module('ag.sdk.model.crop', ['ag.sdk.library', 'ag.sdk.utilities', 'ag.sdk.model.asset', 'ag.sdk.model.asset-factory', 'ag.sdk.model.base']);

sdkModelCrop.provider('Crop', ['AssetFactoryProvider', function (AssetFactoryProvider) {
    this.$get = ['Base', 'asJson', 'Asset', 'computedProperty', 'inheritModel', 'privateProperty', 'naturalSort', 'readOnlyProperty', 'safeMath', 'underscore',
        function (Base, asJson, Asset, computedProperty, inheritModel, privateProperty, naturalSort, readOnlyProperty, safeMath, underscore) {
            function Crop (attrs) {
                Asset.apply(this, arguments);

                Base.initializeObject(this.data, 'inspections', []);
                Base.initializeObject(this.data, 'problems', []);
                Base.initializeObject(this.data, 'season', 'Unknown');
                Base.initializeObject(this.data, 'zones', []);

                computedProperty(this, 'flower', function () {
                    return flowerTypes[this.data.crop] || POD;
                });

                computedProperty(this, 'problems', function () {
                    return this.data.problems;
                });

                computedProperty(this, 'zones', function () {
                    return this.data.zones;
                });

                privateProperty(this, 'addProblem', function (problem) {
                    addItem(this, 'problems', problem);
                });

                privateProperty(this, 'addZone', function (zone) {
                    addItem(this, 'zones', zone);
                });

                privateProperty(this, 'removeProblem', function (problem) {
                    removeItem(this, 'problems', problem);
                });

                privateProperty(this, 'removeZone', function (zone) {
                    removeItem(this, 'zones', zone);
                });

                this.type = 'crop';
            }

            inheritModel(Crop, Asset);

            function addItem (instance, dataStore, item) {
                if (item) {
                    instance.data[dataStore] = underscore.chain(instance.data[dataStore])
                        .reject(underscore.identity({uuid: item.uuid}))
                        .union([asJson(item)])
                        .value()
                        .sort(function (a, b) {
                            return naturalSort(a.createdAt, b.createdAt);
                        });

                    updatePlantedArea(instance);
                    instance.$dirty = true;
                }
            }

            function removeItem (instance, dataStore, item) {
                if (item) {
                    instance.data[dataStore] = underscore.reject(instance.data[dataStore], underscore.identity({uuid: item.uuid}));
                    updatePlantedArea(instance);
                    instance.$dirty = true;
                }
            }

            function updatePlantedArea (instance) {
                instance.data.plantedArea = underscore.reduce(instance.zones, function (total, zone) {
                    return safeMath.plus(total, zone.size);
                }, 0);
            }

            var EAR = 'ear',
                FLOWER = 'flower',
                POD = 'pod',
                PANICLE = 'panicle',
                SPIKELET = 'spikelet';

            var flowerTypes = {
                'Dry Bean': POD,
                'Grain Sorghum': PANICLE,
                'Maize': EAR,
                'Maize (White)': EAR,
                'Maize (Yellow)': EAR,
                'Sunflower': FLOWER,
                'Wheat': SPIKELET,
                'Soya Bean': POD
            };

            Crop.validates(underscore.defaults({
                type: {
                    required: true,
                    equal: {
                        to: 'crop'
                    }
                }
            }, Asset.validations));

            return Crop;
        }];

    AssetFactoryProvider.add('crop', 'Crop');
}]);

sdkModelCrop.factory('CropProblem', ['generateUUID', 'inheritModel', 'Model', 'moment', 'readOnlyProperty', 'underscore',
    function (generateUUID, inheritModel, Model, moment, readOnlyProperty, underscore) {
        function CropProblem (attrs) {
            Model.Base.apply(this, arguments);

            if (underscore.isUndefined(attrs) || arguments.length === 0) return;

            this.createdAt = attrs.createdAt || moment().format('YYYY-MM-DD');
            this.description = attrs.description;
            this.loc = attrs.loc;
            this.size = attrs.size;
            this.type = attrs.type;
            this.uuid = attrs.uuid || generateUUID();
        }

        inheritModel(CropProblem, Model.Base);

        readOnlyProperty(CropProblem, 'problemTypes', [
            'Disease',
            'Fading',
            'Uneven',
            'Other',
            'Root',
            'Shortage',
            'Weed']);

        CropProblem.validates({
            description: {
                requiredIf: function (value, instance) {
                    return instance.type === 'Other';
                },
                length: {
                    min: 0,
                    max: 255
                }
            },
            type: {
                required: true,
                inclusion: {
                    in: CropProblem.problemTypes
                }
            },
            uuid: {
                format: {
                    uuid: true
                }
            }
        });

        return CropProblem;
    }]);

sdkModelCrop.factory('CropZone', ['computedProperty', 'generateUUID', 'inheritModel', 'Model', 'moment', 'naturalSort', 'readOnlyProperty', 'underscore',
    function (computedProperty, generateUUID, inheritModel, Model, moment, naturalSort, readOnlyProperty, underscore) {
        function CropZone (attrs) {
            Model.Base.apply(this, arguments);

            computedProperty(this, 'cultivars', function () {
                return CropZone.cultivarsByCrop[this.crop] || [];
            });

            computedProperty(this, 'growthStages', function () {
                return cropGrowthStages[this.crop] || growthStages[0];
            });

            computedProperty(this, 'leavesPerPlant', function () {
                return cultivarLeaves[this.cultivar] || 22;
            }, {
                enumerable: true
            });

            computedProperty(this, 'typeRequired', function () {
                return s.include(this.crop, 'Maize');
            });

            if (underscore.isUndefined(attrs) || arguments.length === 0) return;

            this.createdAt = attrs.createdAt || moment().format('YYYY-MM-DD');
            this.crop = attrs.crop;
            this.cultivar = attrs.cultivar;
            this.emergenceDate = attrs.emergenceDate;
            this.growthStage = attrs.growthStage;
            this.inRows = attrs.inRows;
            this.loc = attrs.loc;
            this.plantsHa = attrs.plantsHa;
            this.rowWidth = attrs.rowWidth;
            this.seedProvider = attrs.seedProvider;
            this.size = attrs.size;
            this.type = attrs.type;
            this.uuid = attrs.uuid || generateUUID();
        }

        inheritModel(CropZone, Model.Base);

        var AFGRI = 'Afgri',
            ARGICOL = 'Agricol',
            AGRIOCARE = 'Agriocare',
            ALL_GROW = 'All-Grow Seed',
            CAPSTONE = 'Capstone',
            DELALB_MONSANTO = 'Dekalb (Monsanto)',
            DELTA_SEED = 'Delta Seeds',
            DRY_BEAN = 'Dry Bean Seed Pty (Ltd)',
            KLEIN_KAROO = 'Klein Karoo',
            LINKSAAD = 'Linksaad',
            PANNAR = 'Pannar',
            PIONEER = 'Pioneer',
            SENSAKO = 'Sensako',
            SENSAKO_MONSANTO = 'Sensako (Monsanto)',
            OTHER = 'Other';

        var MAIZE_YELLOW = [
            [AFGRI,'AFG 4222 B'],
            [AFGRI,'AFG 4244'],
            [AFGRI,'AFG 4270 B'],
            [AFGRI,'AFG 4410'],
            [AFGRI,'AFG 4412 B'],
            [AFGRI,'AFG 4414'],
            [AFGRI,'AFG 4416 B'],
            [AFGRI,'AFG 4434 R'],
            [AFGRI,'AFG 4440'],
            [AFGRI,'AFG 4448'],
            [AFGRI,'AFG 4452 B'],
            [AFGRI,'AFG 4474 R'],
            [AFGRI,'AFG 4476'],
            [AFGRI,'AFG 4478 BR'],
            [AFGRI,'AFG 4512'],
            [AFGRI,'AFG 4520'],
            [AFGRI,'AFG 4522 B'],
            [AFGRI,'AFG 4530'],
            [AFGRI,'AFG 4540'],
            [AFGRI,'AFG 4546'],
            [AFGRI,'AFG 4548'],
            [AFGRI,'AFG 4566 B'],
            [AFGRI,'AFG 4572 R'],
            [AFGRI,'AFG 4660'],
            [AFGRI,'AFG 4664'],
            [AFGRI,'DK 618'],
            [ARGICOL,'IMP 50-90 BR'],
            [ARGICOL,'IMP 51-22 B'],
            [ARGICOL,'IMP 51-92'],
            [ARGICOL,'IMP 51-92 R'],
            [ARGICOL,'QS 7646'],
            [ARGICOL,'SC 602'],
            [ARGICOL,'SC 608'],
            [CAPSTONE,'CAP 121-30'],
            [CAPSTONE,'CAP 122-60'],
            [CAPSTONE,'CAP 130-120'],
            [CAPSTONE,'CAP 130-140'],
            [CAPSTONE,'CAP 444 NG'],
            [CAPSTONE,'CAP 766 NG'],
            [CAPSTONE,'CAP 9004'],
            [CAPSTONE,'CAP 9444 NG'],
            [DELALB_MONSANTO,'DKC 61-90'],
            [DELALB_MONSANTO,'DKC 62-80 BR'],
            [DELALB_MONSANTO,'DKC 62-80 BR GEN'],
            [DELALB_MONSANTO,'DKC 62-84 R'],
            [DELALB_MONSANTO,'DKC 64-78 BR'],
            [DELALB_MONSANTO,'DKC 64-78 BR GEN'],
            [DELALB_MONSANTO,'DKC 66-32 B'],
            [DELALB_MONSANTO,'DKC 66-36 R'],
            [DELALB_MONSANTO,'DKC 66-60 BR'],
            [DELALB_MONSANTO,'DKC 73-70 B GEN'],
            [DELALB_MONSANTO,'DKC 73-72'],
            [DELALB_MONSANTO,'DKC 73-74 BR GEN'],
            [DELALB_MONSANTO,'DKC 73-76 R'],
            [DELALB_MONSANTO,'DKC 80-10'],
            [DELALB_MONSANTO,'DKC 80-12 B GEN'],
            [DELALB_MONSANTO,'DKC 80-30 R'],
            [DELALB_MONSANTO,'DKC 80-40 BR GEN'],
            [DELTA_SEED,'Amber'],
            [DELTA_SEED,'DE 2004'],
            [DELTA_SEED,'DE 2006'],
            [DELTA_SEED,'DE 2016'],
            [DELTA_SEED,'DE 222'],
            [KLEIN_KAROO,'Helen'],
            [KLEIN_KAROO,'KKS 8202'],
            [KLEIN_KAROO,'KKS 8204 B'],
            [KLEIN_KAROO,'KKS 8400'],
            [KLEIN_KAROO,'KKS 8402'],
            [LINKSAAD,'LS 8518'],
            [LINKSAAD,'LS 8524 R'],
            [LINKSAAD,'LS 8526'],
            [LINKSAAD,'LS 8528 R'],
            [LINKSAAD,'LS 8532 B'],
            [LINKSAAD,'LS 8536 B'],
            [PANNAR,'BG 3268'],
            [PANNAR,'BG 3292'],
            [PANNAR,'BG 3492BR'],
            [PANNAR,'BG 3568R'],
            [PANNAR,'BG 3592R'],
            [PANNAR,'BG 3768BR'],
            [PANNAR,'BG 4296'],
            [PANNAR,'BG 6308B'],
            [PANNAR,'PAN 14'],
            [PANNAR,'PAN 3D-736 BR'],
            [PANNAR,'PAN 3P-502 R'],
            [PANNAR,'PAN 3P-730 BR'],
            [PANNAR,'PAN 3Q-222'],
            [PANNAR,'PAN 3Q-240'],
            [PANNAR,'PAN 3Q-740 BR'],
            [PANNAR,'PAN 3R-644 R'],
            [PANNAR,'PAN 4P-228'],
            [PANNAR,'PAN 4P-716 BR'],
            [PANNAR,'PAN 6126 '],
            [PANNAR,'PAN 66'],
            [PANNAR,'PAN 6616'],
            [PANNAR,'PAN 6P-110'],
            [PANNAR,'PAN 6P110'],
            [PANNAR,'PAN 6Q-408B'],
            [PANNAR,'PAN 6Q-508 R'],
            [PANNAR,'PAN 6Q-708 BR'],
            [PIONEER,'P 1615 R'],
            [PIONEER,'P 2048'],
            [PIONEER,'Phb 31D21 B'],
            [PIONEER,'Phb 31D24'],
            [PIONEER,'Phb 31D46 BR'],
            [PIONEER,'Phb 31D48 B'],
            [PIONEER,'Phb 31G54 BR'],
            [PIONEER,'Phb 31G56 R'],
            [PIONEER,'Phb 31K58 B'],
            [PIONEER,'Phb 32D95 BR'],
            [PIONEER,'Phb 32D96 B'],
            [PIONEER,'Phb 32D99'],
            [PIONEER,'Phb 32P68 R'],
            [PIONEER,'Phb 32T50'],
            [PIONEER,'Phb 32W71'],
            [PIONEER,'Phb 32W72 B'],
            [PIONEER,'Phb 33A14 B'],
            [PIONEER,'Phb 33H52 B'],
            [PIONEER,'Phb 33H56'],
            [PIONEER,'Phb 33Y72 B'],
            [PIONEER,'Phb 33Y74'],
            [PIONEER,'Phb 3442'],
            [PIONEER,'Phb 34N44 B'],
            [PIONEER,'Phb 34N45 BR'],
            [PIONEER,'Phb 35T05 R'],
            [SENSAKO_MONSANTO,'SNK 2472'],
            [SENSAKO_MONSANTO,'SNK 2682'],
            [SENSAKO_MONSANTO,'SNK 2778'],
            [SENSAKO_MONSANTO,'SNK 2900'],
            [SENSAKO_MONSANTO,'SNK 2942'],
            [SENSAKO_MONSANTO,'SNK 2972'],
            [SENSAKO_MONSANTO,'SNK 6326 B'],
            [SENSAKO_MONSANTO,'SNK 7510 Y'],
            [SENSAKO_MONSANTO,'SNK 8520'],
            [OTHER,'Brasco'],
            [OTHER,'Cobber Flint'],
            [OTHER,'Cumbre'],
            [OTHER,'Energy'],
            [OTHER,'Gold Finger'],
            [OTHER,'High Flyer'],
            [OTHER,'IMP 50-10 R'],
            [OTHER,'IMP 51-22'],
            [OTHER,'IMP 52-12'],
            [OTHER,'MEH 114'],
            [OTHER,'MMH 1765'],
            [OTHER,'MMH 8825'],
            [OTHER,'Maverik'],
            [OTHER,'NK Arma'],
            [OTHER,'NK MAYOR B'],
            [OTHER,'NS 5000'],
            [OTHER,'NS 5004'],
            [OTHER,'NS 5066'],
            [OTHER,'NS 5914'],
            [OTHER,'NS 5916'],
            [OTHER,'NS 5918'],
            [OTHER,'NS 5920'],
            [OTHER,'Premium Flex'],
            [OTHER,'QS 7608'],
            [OTHER,'RO 430'],
            [OTHER,'SA 24'],
            [OTHER,'SABI 7004'],
            [OTHER,'SABI 7200'],
            [OTHER,'Silmaster'],
            [OTHER,'Syncerus'],
            [OTHER,'US 9570'],
            [OTHER,'US 9580'],
            [OTHER,'US 9600'],
            [OTHER,'US 9610'],
            [OTHER,'US 9620'],
            [OTHER,'US 9770'],
            [OTHER,'US 9772'],
            [OTHER,'Woodriver']
        ];

        var MAIZE_WHITE = [
            [AFGRI,'AFG 4211'],
            [AFGRI,'AFG 4321'],
            [AFGRI,'AFG 4331'],
            [AFGRI,'AFG 4333'],
            [AFGRI,'AFG 4361'],
            [AFGRI,'AFG 4383'],
            [AFGRI,'AFG 4411'],
            [AFGRI,'AFG 4445'],
            [AFGRI,'AFG 4447'],
            [AFGRI,'AFG 4471'],
            [AFGRI,'AFG 4475 B'],
            [AFGRI,'AFG 4477'],
            [AFGRI,'AFG 4479 R'],
            [AFGRI,'AFG 4501'],
            [AFGRI,'AFG 4517'],
            [AFGRI,'AFG 4555'],
            [AFGRI,'AFG 4571 B'],
            [AFGRI,'AFG 4573 B'],
            [AFGRI,'AFG 4575'],
            [AFGRI,'AFG 4577 B'],
            [AFGRI,'AFG 4579 B'],
            [AFGRI,'AFG 4581 BR'],
            [AFGRI,'AFG 4611'],
            [AFGRI,'AFG 4663'],
            [AFGRI,'AFRIC 1'],
            [ARGICOL,'IMP 52-11'],
            [ARGICOL,'SC 701'],
            [ARGICOL,'SC 709'],
            [CAPSTONE,'CAP 341 NG'],
            [CAPSTONE,'CAP 341 T NG'],
            [CAPSTONE,'CAP 441 NG'],
            [CAPSTONE,'CAP 775 NG'],
            [CAPSTONE,'CAP 9001'],
            [CAPSTONE,'CAP 9013'],
            [CAPSTONE,'CAP 9421'],
            [DELALB_MONSANTO,'CRN 3505'],
            [DELALB_MONSANTO,'CRN 4141'],
            [DELALB_MONSANTO,'DKC 77-61 B'],
            [DELALB_MONSANTO,'DKC 77-85 B GEN'],
            [DELALB_MONSANTO,'DKC 78-15 B'],
            [DELALB_MONSANTO,'DKC 78-17 B'],
            [DELALB_MONSANTO,'DKC 78-35 R'],
            [DELALB_MONSANTO,'DKC 78-45 BR'],
            [DELALB_MONSANTO,'DKC 78-45 BR GEN'],
            [DELALB_MONSANTO,'DKC 79-05'],
            [DELTA_SEED,'DE 111'],
            [DELTA_SEED,'DE 303'],
            [KLEIN_KAROO,'KKS 4383'],
            [KLEIN_KAROO,'KKS 4445'],
            [KLEIN_KAROO,'KKS 4447'],
            [KLEIN_KAROO,'KKS 4471'],
            [KLEIN_KAROO,'KKS 4473'],
            [KLEIN_KAROO,'KKS 4477'],
            [KLEIN_KAROO,'KKS 4479 R'],
            [KLEIN_KAROO,'KKS 4485'],
            [KLEIN_KAROO,'KKS 4501'],
            [KLEIN_KAROO,'KKS 4517'],
            [KLEIN_KAROO,'KKS 4519'],
            [KLEIN_KAROO,'KKS 4555'],
            [KLEIN_KAROO,'KKS 4575'],
            [KLEIN_KAROO,'KKS 4581 BR'],
            [KLEIN_KAROO,'KKS 8401'],
            [LINKSAAD,'LS 8519'],
            [LINKSAAD,'LS 8529'],
            [LINKSAAD,'LS 8533 R'],
            [LINKSAAD,'LS 8535 B'],
            [LINKSAAD,'LS 8537'],
            [LINKSAAD,'LS 8539 B'],
            [PANNAR,'BG 5485B'],
            [PANNAR,'BG 5685R'],
            [PANNAR,'BG4201'],
            [PANNAR,'BG4401B'],
            [PANNAR,'BG5285'],
            [PANNAR,'BG5785BR'],
            [PANNAR,'BG6683R'],
            [PANNAR,'PAN 413'],
            [PANNAR,'PAN 4P-767BR'],
            [PANNAR,'PAN 53'],
            [PANNAR,'PAN 5Q-649 R'],
            [PANNAR,'PAN 5Q-749 BR'],
            [PANNAR,'PAN 5Q-751BR'],
            [PANNAR,'PAN 6227'],
            [PANNAR,'PAN 6479'],
            [PANNAR,'PAN 6611'],
            [PANNAR,'PAN 6671'],
            [PANNAR,'PAN 67'],
            [PANNAR,'PAN 6777'],
            [PANNAR,'PAN 69'],
            [PANNAR,'PAN 6Q-745BR'],
            [PANNAR,'PAN 93'],
            [PANNAR,'PAN413'],
            [PANNAR,'PAN53'],
            [PANNAR,'PAN6Q245'],
            [PANNAR,'PAN6Q345CB'],
            [PANNAR,'SC 701 (Green mealie)'],
            [PIONEER,'P 2369 W'],
            [PIONEER,'P 2653 WB'],
            [PIONEER,'P 2823 WB'],
            [PIONEER,'P 2961 W'],
            [PIONEER,'Phb 30B95 B'],
            [PIONEER,'Phb 30B97 BR'],
            [PIONEER,'Phb 30D04 R'],
            [PIONEER,'Phb 30D07 B'],
            [PIONEER,'Phb 30D09 BR'],
            [PIONEER,'Phb 30Y79 B'],
            [PIONEER,'Phb 30Y81 R'],
            [PIONEER,'Phb 30Y83'],
            [PIONEER,'Phb 31M09'],
            [PIONEER,'Phb 31M84 BR'],
            [PIONEER,'Phb 31T91'],
            [PIONEER,'Phb 31V31'],
            [PIONEER,'Phb 3210B'],
            [PIONEER,'Phb 32A05 B'],
            [PIONEER,'Phb 32B07 BR'],
            [PIONEER,'Phb 32Y85'],
            [PIONEER,'Phb 32Y87 B'],
            [SENSAKO_MONSANTO,'SNK 2021'],
            [SENSAKO_MONSANTO,'SNK 2147'],
            [SENSAKO_MONSANTO,'SNK 2401'],
            [SENSAKO_MONSANTO,'SNK 2551'],
            [SENSAKO_MONSANTO,'SNK 2721'],
            [SENSAKO_MONSANTO,'SNK 2911'],
            [SENSAKO_MONSANTO,'SNK 2969'],
            [SENSAKO_MONSANTO,'SNK 6025'],
            [SENSAKO_MONSANTO,'SNK 7811 B'],
            [OTHER,'CG 4141'],
            [OTHER,'GM 2000'],
            [OTHER,'KGALAGADI'],
            [OTHER,'MRI 514'],
            [OTHER,'MRI 624'],
            [OTHER,'NG 761'],
            [OTHER,'NS 5913'],
            [OTHER,'NS 5917'],
            [OTHER,'NS 5919'],
            [OTHER,'PGS 7053'],
            [OTHER,'PGS 7061'],
            [OTHER,'PGS 7071'],
            [OTHER,'PLATINUM'],
            [OTHER,'Panthera'],
            [OTHER,'QS 7707'],
            [OTHER,'RO 413'],
            [OTHER,'RO 413'],
            [OTHER,'RO 419'],
            [OTHER,'SAFFIER'],
            [OTHER,'SC 401'],
            [OTHER,'SC 403'],
            [OTHER,'SC 405'],
            [OTHER,'SC 407'],
            [OTHER,'SC 513'],
            [OTHER,'SC 627'],
            [OTHER,'SC 631'],
            [OTHER,'SC 633'],
            [OTHER,'SC 713'],
            [OTHER,'SC 715'],
            [OTHER,'Scout']];

        readOnlyProperty(CropZone, 'cultivarsByCrop', {
            'Barley':[
                [ARGICOL,'SKG 9'],
                [ARGICOL,'SVG 13'],
                [OTHER,'Clipper'],
                [OTHER,'Cocktail'],
                [OTHER,'Puma'],
                [OTHER,'SabbiErica'],
                [OTHER,'SabbiNemesia'],
                [OTHER,'SSG 564'],
                [OTHER,'SSG 585']
            ],
            'Bean (Dry)':[
                [CAPSTONE,'CAP 2000'],
                [CAPSTONE,'CAP 2001'],
                [CAPSTONE,'CAP 2008'],
                [DRY_BEAN,'DBS 310'],
                [DRY_BEAN,'DBS 360'],
                [DRY_BEAN,'DBS 830'],
                [DRY_BEAN,'DBS 840'],
                [DRY_BEAN,'Kranskop HR1'],
                [DRY_BEAN,'OPS RS1'],
                [DRY_BEAN,'OPS RS2'],
                [DRY_BEAN,'OPS RS4'],
                [DRY_BEAN,'OPS-KW1'],
                [DRY_BEAN,'RS 5'],
                [DRY_BEAN,'RS 6'],
                [DRY_BEAN,'RS 7'],
                [PANNAR,'PAN 116'],
                [PANNAR,'PAN 123'],
                [PANNAR,'PAN 128'],
                [PANNAR,'PAN 135'],
                [PANNAR,'PAN 139'],
                [PANNAR,'PAN 146'],
                [PANNAR,'PAN 148'],
                [PANNAR,'PAN 148 Plus'],
                [PANNAR,'PAN 9213'],
                [PANNAR,'PAN 9216'],
                [PANNAR,'PAN 9225'],
                [PANNAR,'PAN 9249'],
                [PANNAR,'PAN 9280'],
                [PANNAR,'PAN 9281'],
                [PANNAR,'PAN 9292'],
                [PANNAR,'PAN 9298'],
                [OTHER,'AFG 470'],
                [OTHER,'AFG 471'],
                [OTHER,'BONUS'],
                [OTHER,'CALEDON'],
                [OTHER,'CARDINAL'],
                [OTHER,'CERRILLOS'],
                [OTHER,'DONGARA'],
                [OTHER,'DPO 820'],
                [OTHER,'JENNY'],
                [OTHER,'KAMIESBERG'],
                [OTHER,'KOMATI'],
                [OTHER,'KRANSKOP'],
                [OTHER,'MAJUBA'],
                [OTHER,'MASKAM'],
                [OTHER,'MINERVA'],
                [OTHER,'MKONDENI'],
                [OTHER,'MKUZI'],
                [OTHER,'RUBY'],
                [OTHER,'SC Silk'],
                [OTHER,'SC Superior'],
                [OTHER,'SEDERBERG'],
                [OTHER,'SSB 20'],
                [OTHER,'STORMBERG'],
                [OTHER,'TEEBUS'],
                [OTHER,'TEEBUS-RCR2'],
                [OTHER,'TEEBUS-RR1'],
                [OTHER,'TYGERBERG'],
                [OTHER,'UKULINGA'],
                [OTHER,'UMTATA'],
                [OTHER,'WERNA']
            ],
            'Canola':[
                [ARGICOL,'Aga Max'],
                [ARGICOL,'AV Garnet'],
                [ARGICOL,'CB Jardee HT'],
                [ARGICOL,'Cobbler'],
                [ARGICOL,'Tawriffic'],
                [KLEIN_KAROO,'Hyola 61'],
                [KLEIN_KAROO,'Rocket CL'],
                [KLEIN_KAROO,'Thunder TT'],
                [KLEIN_KAROO,'Varola 54']
            ],
            'Grain Sorghum':[
                [ARGICOL,'AVENGER GH'],
                [ARGICOL,'DOMINATOR GM'],
                [ARGICOL,'ENFORCER GM'],
                [ARGICOL,'MAXIMIZER'],
                [ARGICOL,'PREMIUM 4065 T GH'],
                [ARGICOL,'PREMIUM 100'],
                [ARGICOL,'NS 5511 GH'],
                [ARGICOL,'NS 5540'],
                [ARGICOL,'NS 5555'],
                [ARGICOL,'NS 5655 GM'],
                [ARGICOL,'NS 5751'],
                [ARGICOL,'NS 5832'],
                [ARGICOL,'TIGER GM'],
                [CAPSTONE,'CAP 1002'],
                [CAPSTONE,'CAP 1003'],
                [CAPSTONE,'CAP 1004'],
                [KLEIN_KAROO,'MR 32 GL'],
                [KLEIN_KAROO,'MR 43 GL'],
                [KLEIN_KAROO,'MR BUSTER GL'],
                [KLEIN_KAROO,'MR PACER'],
                [PANNAR,'PAN 8625 GH'],
                [PANNAR,'PAN 8816 GM'],
                [PANNAR,'PAN 8906 GM'],
                [PANNAR,'PAN 8909 GM'],
                [PANNAR,'PAN 8006 T'],
                [PANNAR,'PAN 8507'],
                [PANNAR,'PAN 8609'],
                [PANNAR,'PAN 8648'],
                [PANNAR,'PAN 8706'],
                [PANNAR,'PAN 8806'],
                [PANNAR,'PAN 8901'],
                [PANNAR,'PAN 8902'],
                [PANNAR,'PAN 8903'],
                [PANNAR,'PAN 8904'],
                [PANNAR,'PAN 8905'],
                [PANNAR,'PAN 8906'],
                [PANNAR,'PAN 8907'],
                [PANNAR,'PAN 8908'],
                [PANNAR,'PAN 8909'],
                [PANNAR,'PAN 8911'],
                [PANNAR,'PAN 8912'],
                [PANNAR,'PAN 8913'],
                [PANNAR,'PAN 8914'],
                [PANNAR,'PAN 8915'],
                [PANNAR,'PAN 8916'],
                [PANNAR,'PAN 8918'],
                [PANNAR,'PAN 8919'],
                [PANNAR,'PAN 8920'],
                [PANNAR,'PAN 8921'],
                [PANNAR,'PAN 8922'],
                [PANNAR,'PAN 8923'],
                [PANNAR,'PAN 8924'],
                [PANNAR,'PAN 8925'],
                [PANNAR,'PAN 8926'],
                [PANNAR,'PAN 8927'],
                [PANNAR,'PAN 8928'],
                [PANNAR,'PAN 8929'],
                [PANNAR,'PAN 8930'],
                [PANNAR,'PAN 8931'],
                [PANNAR,'PAN 8932'],
                [PANNAR,'PAN 8933'],
                [PANNAR,'PAN 8936'],
                [PANNAR,'PAN 8937'],
                [PANNAR,'PAN 8938'],
                [PANNAR,'PAN 8939'],
                [PANNAR,'PAN 8940'],
                [PANNAR,'PAN 8966'],
                [OTHER,'APN 881'],
                [OTHER,'MACIA-SA'],
                [OTHER,'NK 8830'],
                [OTHER,'OVERFLOW'],
                [OTHER,'SA 1302-M27'],
                [OTHER,'TITAN'],
                [OTHER,'X868']
            ],
            'Maize': underscore.union(MAIZE_YELLOW, MAIZE_WHITE).sort(function (itemA, itemB) {
                return naturalSort(itemA.join(), itemB.join());
            }),
            'Maize (Yellow)': MAIZE_YELLOW,
            'Maize (White)': MAIZE_WHITE,
            'Oat':[
                [ARGICOL,'Magnifico'],
                [ARGICOL,'Maida'],
                [ARGICOL,'Nugene'],
                [ARGICOL,'Overberg'],
                [ARGICOL,'Pallinup'],
                [ARGICOL,'Saia'],
                [ARGICOL,'SWK001'],
                [SENSAKO_MONSANTO],
                [SENSAKO_MONSANTO,'SSH 39W'],
                [SENSAKO_MONSANTO,'SSH 405'],
                [SENSAKO_MONSANTO,'SSH 421'],
                [SENSAKO_MONSANTO,'SSH 423'],
                [SENSAKO_MONSANTO,'SSH 491'],
                [OTHER,'Drakensberg'],
                [OTHER,'H06/19'],
                [OTHER,'H06/20'],
                [OTHER,'H07/04'],
                [OTHER,'H07/05'],
                [OTHER,'Heros'],
                [OTHER,'Kompasberg'],
                [OTHER,'Le Tucana'],
                [OTHER,'Maluti'],
                [OTHER,'Potoroo'],
                [OTHER,'Witteberg']
            ],
            'Soya Bean':[
                [AGRIOCARE,'AGC 58007 R'],
                [AGRIOCARE,'AGC 60104 R'],
                [AGRIOCARE,'AGC 64107 R'],
                [AGRIOCARE,'AS 4801 R'],
                [LINKSAAD,'LS 6146 R'],
                [LINKSAAD,'LS 6150 R'],
                [LINKSAAD,'LS 6161 R'],
                [LINKSAAD,'LS 6164 R'],
                [LINKSAAD,'LS 6248 R'],
                [LINKSAAD,'LS 6261 R'],
                [LINKSAAD,'LS 6444 R'],
                [LINKSAAD,'LS 6466 R'],
                [PANNAR,'A 5409 RG'],
                [PANNAR,'PAN 1454 R'],
                [PANNAR,'PAN 1583 R'],
                [PANNAR,'PAN 1664 R'],
                [PANNAR,'PAN 1666 R'],
                [PIONEER,'Phb 94Y80 R'],
                [PIONEER,'Phb 95B53 R'],
                [PIONEER,'Phb 95Y20 R'],
                [PIONEER,'Phb 95Y40 R'],
                [OTHER,'AG 5601'],
                [OTHER,'AMSTEL NO 1'],
                [OTHER,'DUMELA'],
                [OTHER,'DUNDEE'],
                [OTHER,'EGRET'],
                [OTHER,'HERON'],
                [OTHER,'HIGHVELD TOP'],
                [OTHER,'IBIS 2000'],
                [OTHER,'JF 91'],
                [OTHER,'JIMMY'],
                [OTHER,'KIAAT'],
                [OTHER,'KNAP'],
                [OTHER,'LEX 1233 R'],
                [OTHER,'LEX 1235 R'],
                [OTHER,'LEX 2257 R'],
                [OTHER,'LEX 2685 R'],
                [OTHER,'LIGHTNING'],
                [OTHER,'MARULA'],
                [OTHER,'MARUTI'],
                [OTHER,'MOPANIE'],
                [OTHER,'MPIMBO'],
                [OTHER,'MUKWA'],
                [OTHER,'NQUTU'],
                [OTHER,'OCTA'],
                [OTHER,'SONOP'],
                [OTHER,'SPITFIRE'],
                [OTHER,'STORK'],
                [OTHER,'TAMBOTIE'],
                [OTHER,'WENNER']
            ],
            'Sugarcane':[
                [OTHER,'ACRUNCH'],
                [OTHER,'BONITA'],
                [OTHER,'CHIEFTAIN'],
                [OTHER,'EARLISWEET'],
                [OTHER,'GLADIATOR'],
                [OTHER,'GSS 9299'],
                [OTHER,'HOLLYWOOD'],
                [OTHER,'HONEYMOON'],
                [OTHER,'INFERNO'],
                [OTHER,'JUBILEE'],
                [OTHER,'MADHUR'],
                [OTHER,'MAJESTY'],
                [OTHER,'MANTRA'],
                [OTHER,'MATADOR'],
                [OTHER,'MAX'],
                [OTHER,'MEGATON'],
                [OTHER,'MMZ 9903'],
                [OTHER,'ORLA'],
                [OTHER,'OSCAR'],
                [OTHER,'OVERLAND'],
                [OTHER,'PRIMEPLUS'],
                [OTHER,'RUSALTER'],
                [OTHER,'RUSTICO'],
                [OTHER,'RUSTLER'],
                [OTHER,'SENTINEL'],
                [OTHER,'SHIMMER'],
                [OTHER,'STAR 7708'],
                [OTHER,'STAR 7713'],
                [OTHER,'STAR 7714'],
                [OTHER,'STAR 7715'],
                [OTHER,'STAR 7717'],
                [OTHER,'STAR 7718'],
                [OTHER,'STAR 7719'],
                [OTHER,'STETSON'],
                [OTHER,'SWEET SUCCESS'],
                [OTHER,'SWEET SURPRISE'],
                [OTHER,'SWEET TALK'],
                [OTHER,'TENDER TREAT'],
                [OTHER,'WINSTAR']
            ],
            'Sunflower':[
                [ARGICOL,'AGSUN 5161 CL'],
                [ARGICOL,'AGSUN 5182 CL'],
                [ARGICOL,'Agsun 5264'],
                [ARGICOL,'Agsun 5671'],
                [ARGICOL,'Agsun 8251'],
                [ARGICOL,'Nonjana'],
                [ARGICOL,'SUNSTRIPE'],
                [KLEIN_KAROO,'AFG 271'],
                [KLEIN_KAROO,'HYSUN 333'],
                [KLEIN_KAROO,'KKS 318'],
                [KLEIN_KAROO,'NK ADAGIO'],
                [KLEIN_KAROO,'NK Armoni'],
                [KLEIN_KAROO,'NK FERTI'],
                [KLEIN_KAROO,'Sirena'],
                [KLEIN_KAROO,'Sunbird'],
                [PANNAR,'PAN 7033'],
                [PANNAR,'PAN 7049'],
                [PANNAR,'PAN 7050'],
                [PANNAR,'PAN 7057'],
                [PANNAR,'PAN 7063 CL'],
                [PANNAR,'PAN 7080'],
                [PANNAR,'PAN 7086 HO'],
                [PANNAR,'PAN 7095 CL'],
                [PANNAR,'PAN 7351'],
                [OTHER,'Ella'],
                [OTHER,'Grainco Sunstripe'],
                [OTHER,'HV 3037'],
                [OTHER,'HYSUN 334'],
                [OTHER,'HYSUN 338'],
                [OTHER,'HYSUN 346'],
                [OTHER,'HYSUN 350'],
                [OTHER,'Jade Emperor'],
                [OTHER,'Marica-2'],
                [OTHER,'NK Adagio CL'],
                [OTHER,'Nallimi CL'],
                [OTHER,'SEA 2088 CL AO'],
                [OTHER,'SY 4045'],
                [OTHER,'SY 4200'],
                [OTHER,'Sikllos CL'],
                [OTHER,'WBS 3100']
            ],
            'Triticale':[
                [ARGICOL,'AG Beacon'],
                [ARGICOL,'Rex'],
                [PANNAR,'PAN 248'],
                [PANNAR,'PAN 299'],
                [OTHER,'Bacchus'],
                [OTHER,'Cloc 1'],
                [OTHER,'Cultivars'],
                [OTHER,'Falcon'],
                [OTHER,'Ibis'],
                [OTHER,'Kiewiet'],
                [OTHER,'Korhaan'],
                [OTHER,'Tobie'],
                [OTHER,'US 2009'],
                [OTHER,'US 2010'],
                [OTHER,'US2007']
            ],
            'Wheat':[
                [AFGRI,'AFG 554-8'],
                [AFGRI,'AFG 75-3'],
                [ALL_GROW,'BUFFELS'],
                [ALL_GROW,'DUZI'],
                [ALL_GROW,'KARIEGA'],
                [ALL_GROW,'KROKODIL'],
                [ALL_GROW,'SABIE'],
                [ALL_GROW,'STEENBRAS'],
                [KLEIN_KAROO,'HARTBEES'],
                [KLEIN_KAROO,'KOMATI'],
                [KLEIN_KAROO,'KOONAP'],
                [KLEIN_KAROO,'MATLABAS'],
                [KLEIN_KAROO,'SELATI'],
                [KLEIN_KAROO,'SENQU'],
                [SENSAKO,'CRN 826'],
                [SENSAKO,'ELANDS'],
                [SENSAKO,'SST 015'],
                [SENSAKO,'SST 026'],
                [SENSAKO,'SST 027'],
                [SENSAKO,'SST 035'],
                [SENSAKO,'SST 036'],
                [SENSAKO,'SST 037'],
                [SENSAKO,'SST 039'],
                [SENSAKO,'SST 047'],
                [SENSAKO,'SST 056'],
                [SENSAKO,'SST 057'],
                [SENSAKO,'SST 065'],
                [SENSAKO,'SST 077'],
                [SENSAKO,'SST 087'],
                [SENSAKO,'SST 088'],
                [SENSAKO,'SST 094'],
                [SENSAKO,'SST 096'],
                [SENSAKO,'SST 107'],
                [SENSAKO,'SST 124'],
                [SENSAKO,'SST 308'],
                [SENSAKO,'SST 316'],
                [SENSAKO,'SST 317'],
                [SENSAKO,'SST 319'],
                [SENSAKO,'SST 322'],
                [SENSAKO,'SST 333'],
                [SENSAKO,'SST 334'],
                [SENSAKO,'SST 347'],
                [SENSAKO,'SST 356'],
                [SENSAKO,'SST 363'],
                [SENSAKO,'SST 366'],
                [SENSAKO,'SST 367'],
                [SENSAKO,'SST 374'],
                [SENSAKO,'SST 387'],
                [SENSAKO,'SST 398'],
                [SENSAKO,'SST 399'],
                [SENSAKO,'SST 802'],
                [SENSAKO,'SST 805'],
                [SENSAKO,'SST 806'],
                [SENSAKO,'SST 807'],
                [SENSAKO,'SST 815'],
                [SENSAKO,'SST 816'],
                [SENSAKO,'SST 822'],
                [SENSAKO,'SST 825'],
                [SENSAKO,'SST 835'],
                [SENSAKO,'SST 843'],
                [SENSAKO,'SST 866'],
                [SENSAKO,'SST 867'],
                [SENSAKO,'SST 875'],
                [SENSAKO,'SST 876'],
                [SENSAKO,'SST 877'],
                [SENSAKO,'SST 878'],
                [SENSAKO,'SST 884'],
                [SENSAKO,'SST 885'],
                [SENSAKO,'SST 886'],
                [SENSAKO,'SST 895'],
                [SENSAKO,'SST 896'],
                [SENSAKO,'SST 935'],
                [SENSAKO,'SST 936'],
                [SENSAKO,'SST 946'],
                [SENSAKO,'SST 954'],
                [SENSAKO,'SST 963'],
                [SENSAKO,'SST 964'],
                [SENSAKO,'SST 966'],
                [SENSAKO,'SST 972'],
                [SENSAKO,'SST 983'],
                [SENSAKO,'SST 0127'],
                [SENSAKO,'SST 1327'],
                [SENSAKO,'SST 3137'],
                [SENSAKO,'SST 8125'],
                [SENSAKO,'SST 8126'],
                [SENSAKO,'SST 8134'],
                [SENSAKO,'SST 8135'],
                [SENSAKO,'SST 8136'],
                [PANNAR,'PAN 3118'],
                [PANNAR,'PAN 3120'],
                [PANNAR,'PAN 3122'],
                [PANNAR,'PAN 3144'],
                [PANNAR,'PAN 3161'],
                [PANNAR,'PAN 3172'],
                [PANNAR,'PAN 3195'],
                [PANNAR,'PAN 3198'],
                [PANNAR,'PAN 3355'],
                [PANNAR,'PAN 3364'],
                [PANNAR,'PAN 3368'],
                [PANNAR,'PAN 3369'],
                [PANNAR,'PAN 3377'],
                [PANNAR,'PAN 3378'],
                [PANNAR,'PAN 3379'],
                [PANNAR,'PAN 3394'],
                [PANNAR,'PAN 3400'],
                [PANNAR,'PAN 3404'],
                [PANNAR,'PAN 3405'],
                [PANNAR,'PAN 3408'],
                [PANNAR,'PAN 3434'],
                [PANNAR,'PAN 3471'],
                [PANNAR,'PAN 3478'],
                [PANNAR,'PAN 3489'],
                [PANNAR,'PAN 3490'],
                [PANNAR,'PAN 3492'],
                [PANNAR,'PAN 3497'],
                [PANNAR,'PAN 3111'],
                [PANNAR,'PAN 3349'],
                [PANNAR,'PAN 3515'],
                [PANNAR,'PAN 3623'],
                [OTHER,'BAVIAANS'],
                [OTHER,'BELINDA'],
                [OTHER,'BETTA-DN'],
                [OTHER,'BIEDOU'],
                [OTHER,'CALEDON'],
                [OTHER,'CARINA'],
                [OTHER,'CAROL'],
                [OTHER,'GARIEP'],
                [OTHER,'HUGENOOT'],
                [OTHER,'INIA'],
                [OTHER,'KOUGA'],
                [OTHER,'KWARTEL'],
                [OTHER,'LIMPOPO'],
                [OTHER,'MacB'],
                [OTHER,'MARICO'],
                [OTHER,'NOSSOB'],
                [OTHER,'OLIFANTS'],
                [OTHER,'SNACK'],
                [OTHER,'TAMBOTI'],
                [OTHER,'TANKWA'],
                [OTHER,'TARKA'],
                [OTHER,'TIMBAVATI'],
                [OTHER,'TUGELA-DN'],
                [OTHER,'UMLAZI'],
                [OTHER,'RATEL']
            ]
        });

        var cultivarLeaves = {
            'Phb 30F40': 23,
            'Phb 31G54 BR': 19,
            'Phb 31G58': 21,
            'Phb 32D95BR': 18,
            'Phb 32D96 B': 18,
            'Phb 32P68 R': 20,
            'Phb 32T50': 18,
            'Phb 32W71': 21,
            'Phb 32W72 B': 20,
            'Phb 33A14 B': 19,
            'Phb 33H56': 20,
            'Phb 33R78 B': 21,
            'Phb 33Y72B': 17,
            'Phb 3442': 21,
            'Phb 30B95 B': 23,
            'Phb 30B97 BR': 23,
            'Phb 30D09 BR': 20,
            'Phb 31M09': 18,
            'Phb 32A05 B': 19,
            'Phb 32B10': 18,
            'Phb 32Y85': 21,
            'Phb 31D48 BR': 21,
            'Phb 32D91 R': 20,
            'Phb 32D99': 20,
            'Phb 32Y68': 20,
            'Phb 3394': 19,
            'Phb 33A13': 19,
            'Phb 33H52 B': 19,
            'Phb 33H54 BR': 19,
            'Phb 33P34': 20,
            'Phb 33P66': 20,
            'Phb 33P67': 20,
            'X 70200 T': 23,
            'X 7268 TR': 21,
            'Phb 30N35': 23,
            'Phb 32A03': 19,
            'Phb 32Y52': 19,
            'Phb 32Y53': 20,
            'Phb 33A03': 19,
            'Phb 30H22': 21,
            'Phb 32P75': 20,
            'Phb 3335': 20,
            'DKC62-74R': 20,
            'DKC62-80BR': 18,
            'DKC64-78BR': 17,
            'DKC66-32B': 21,
            'DKC66-36R': 19,
            'DKC73-70BGEN': 20,
            'DKC73-74BR': 20,
            'DKC73-74BRGEN': 20,
            'DKC73-76R': 20,
            'DKC80-10': 20,
            'DKC80-12B': 20,
            'DKC80-30R': 20,
            'DKC80-40BR': 19,
            'DKC80-40BRGEN': 21,
            'CRN3505': 21,
            'DKC77-61B': 20,
            'DKC77-71R': 20,
            'DKC77-85B': 21,
            'DKC78-15B': 20,
            'DKC78-35BR': 21,
            'DKC78-45BRGEN': 21,
            'DKC 78-79 BR': 21,
            'CRN 3604': 21,
            'CRN 37-60': 20,
            'CRN 4760 B': 23,
            'DKC 63-20': 20,
            'DKC 66-21': 21,
            'DKC 66-38 B': 21,
            'DKC 63-28 R': 21,
            'CRN 3549': 21,
            'DKC 71-21': 20,
            'SNK 2472': 23,
            'SNK 2682': 23,
            'SNK 2778': 23,
            'SNK 2900': 20,
            'SNK 2942': 24,
            'SNK 2972': 21,
            'SNK 6326 B': 21,
            'SNK 8520': 24,
            'SNK 2911': 21,
            'SNK 6025': 18,
            'LS 8504': 20,
            'LS 8512': 20,
            'LS 8518': 19,
            'LS 8522 R': 19,
            'LS 8511': 19,
            'LS 8513': 19,
            'LS 8519': 19,
            'LS 8521 B': 19,
            'LS 8523 B': 19,
            'LS 8527 BR': 19,
            'LS 8506': 21,
            'LS 8508': 20,
            'LS 8524 R': 20,
            'LEX 800': 23,
            'LS 8509': 21,
            'LS 8517': 23,
            'LS 8525': 21,
            'LS 8529': 21,
            'LS 8533 R': 21,
            'LS 8536 B': 19,
            'PAN 3D-432Bt ': 18,
            'PAN 3D-736BR': 18,
            'PAN 3P-502RR': 19,
            'PAN 3P-730BR': 18,
            'PAN 3Q-422B': 18,
            'PAN 3Q-740BR': 19,
            'PAN 3R-644R': 18,
            'PAN 4P-116': 19,
            'PAN 4P-316Bt': 19,
            'PAN 4P-516RR': 20,
            'PAN 4P-716BR': 19,
            'PAN 6114': 19,
            'PAN 6126': 18,
            'PAN 6146': 24,
            'PAN 6236Bt': 18,
            'PAN 6238RR': 18,
            'PAN 6480': 23,
            'PAN 6616': 23,
            'PAN 6724Bt': 25,
            'PAN 6734': 23,
            'PAN 6P-110': 21,
            'PAN 6Q-308 B': 21,
            'PAN 6Q-308 Bt': 21,
            'PAN 6Q-408 CB': 21,
            'PAN 6Q-508R': 21,
            'PAN 6Q-508RR': 20,
            'PAN 4P-767BR': 19,
            'PAN 5Q-433Bt *': 20,
            'PAN 5R-541RR': 19,
            'PAN 6013Bt': 23,
            'PAN 6017': 21,
            'PAN 6043': 23,
            'PAN 6053': 23,
            'PAN 6223Bt': 21,
            'PAN 6479': 23,
            'PAN 6611': 23,
            'PAN 6723': 23,
            'PAN 6777': 25,
            'PAN 6Q-419B': 20,
            'PAN 6Q-445Bt': 21,
            'PAN 6000 Bt': 19,
            'PAN 6012 Bt': 21,
            'PAN 6118': 19,
            'PAN 6124 Bt': 19,
            'PAN 6128 RR': 19,
            'PAN 6256': 24,
            'PAN 6310': 24,
            'PAN 6316': 25,
            'PAN 6320': 25,
            'PAN 6432 B': 23,
            'PAN 6568': 23,
            'PAN 6622': 25,
            'PAN 6710': 21,
            'PAN 6804': 20,
            'PAN 6844': 25,
            'PAN 6994 Bt': 24,
            'PAN 5Q-749 BR': 23,
            'PAN 6243': 24,
            'PAN 6335': 23,
            'PAN 6573': 23,
            'PAN 6633': 23,
            'PAN 6757': 25,
            'PAN 6839': 23,
            'PAN 6Q-321 B': 23,
            'PAN 6Q-345 CB': 21,
            'AFG 4270B': 18,
            'AFG 4412B': 19,
            'AFG 4434R': 20,
            'AFG 4522B': 20,
            'AFG 4530': 19,
            'AFG 4222 B': 19,
            'AFG 4244': 19,
            'AFG 4410': 19,
            'AFG 4414': 20,
            'AFG 4416 B': 20,
            'AFG 4448': 20,
            'AFG 4474 R': 19,
            'AFG 4476': 20,
            'AFG 4512': 23,
            'AFG 4520': 20,
            'AFG 4540': 20,
            'DK 618': 21,
            'EXPG 5002': 20,
            'EXP Stack': 20,
            'AFG 4321': 19,
            'AFG 4331': 20,
            'AFG 4333': 20,
            'AFG 4411': 21,
            'AFG 4445': 21,
            'AFG 4447': 21,
            'AFG 4471': 23,
            'AFG 4475 B': 21,
            'AFG 4477': 20,
            'AFG 4479 R': 21,
            'AFG 4573 B': 21,
            'AFG 4577 B': 21,
            'AFG 4611': 23,
            'KKS 8204B': 15,
            'KKS 4581 BR': 21,
            'KKS 8301': 19,
            'IMP 50 - 90BR': 18,
            'IMP 51 - 22': 19,
            'IMP 51-92': 19,
            'IMP 52-12': 20,
            'NS 5920': 20,
            'QS 7646': 20,
            'BG 5485 B': 23,
            'BG 8285': 23,
            'Brasco': 19,
            'Energy': 18,
            'Gold Finger': 19,
            'Helen': 17,
            'High Flyer': 17,
            'Maverik': 19,
            'NK Arma': 18,
            'QS 7608': 23,
            'SC 506': 19,
            'SC 602': 21,
            'Woodriver': 18,
            'P 1615 R': 19,
            'P 1973 Y': 19,
            'P 2653 WB': 20,
            'P 2048': 20,
            'IMP 52-11 B': 18,
            'Panthera': 21,
            'QS 7707': 23,
            'SC 401': 18,
            'SC 403': 20,
            'SC 405': 20,
            'SC 407': 20,
            'SC 533': 21,
            'SC 719': 24,
            'Scout': 20
        };

        var growthStages = [
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11', 'R12', 'R13', 'R14'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11', 'R12'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6'],
            ['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6']
        ];

        var cropGrowthStages = {
            'Barley': growthStages[1],
            'Bean': growthStages[5],
            'Bean (Broad)': growthStages[5],
            'Bean (Dry)': growthStages[5],
            'Bean (Sugar)': growthStages[5],
            'Bean (Green)': growthStages[5],
            'Bean (Kidney)': growthStages[5],
            'Canola': growthStages[7],
            'Cotton': growthStages[6],
            'Grain Sorghum': growthStages[3],
            'Maize': growthStages[0],
            'Maize (White)': growthStages[0],
            'Maize (Yellow)': growthStages[0],
            'Soya Bean': growthStages[2],
            'Sunflower': growthStages[4],
            'Wheat': growthStages[1],
            'Wheat (Durum)': growthStages[1]
        };

        readOnlyProperty(CropZone, 'maizeTypes', [
            'Commodity',
            'Hybrid',
            'Silo Fodder']);

        CropZone.validates({
            emergenceDate: {
                format: {
                    date: true
                }
            },
            growthStage: {
                required: true,
                inclusion: {
                    in: function (value, instance, field) {
                        return instance.growthStages;
                    }
                }
            },
            plantsHa: {
                required: true,
                range: {
                    from: 0
                },
                numeric: true
            },
            rowWidth: {
                requiredIf: function (value, instance, field) {
                    return instance.inRows;
                },
                range: {
                    from: 0
                },
                numeric: true
            },
            type: {
                requiredIf: function (value, instance, field) {
                    return s.include(instance.crop, 'Maize');
                },
                inclusion: {
                    in: CropZone.maizeTypes
                }
            },
            uuid: {
                format: {
                    uuid: true
                }
            }
        });

        return CropZone;
    }]);


